# Build Stage
FROM mcr.microsoft.com/dotnet/runtime:6.0 AS build
WORKDIR /source
COPY . .
RUN dotnet restore "./MediPort.API/MediPort.API.csproj" --disable-parallel
RUN dotnet publish "./MediPort.API/MediPort.API.csproj" -c release -o /app --no-restore

# Serve Stage
FROM mcr.microsoft.com/dotnet/runtime:6.0
WORKDIR /app
COPY --from=build /app ./

ENTRYPOINT ["dotnet", "MediPort.API.dll"]